name: delconnect
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.9

  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  pull_to_refresh: ^2.0.0
  custom_refresh_indicator: ^4.0.1
  liquid_pull_to_refresh: ^3.0.1
  shared_preferences: ^2.3.3
  flutter_staggered_grid_view: ^0.7.0
  iconsax: ^0.0.8
  cloud_firestore: ^5.5.0
  provider: ^6.1.2
  image_picker: ^1.1.2
  http: ^1.2.2
  cloudinary_public: ^0.23.1
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/fonts/Inter/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
