// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4tKVHikdYaRBEdbT7Rc-GOgAz25Z4qIU',
    appId: '1:1041754221282:web:dc275e2feb9a8b529e8cbb',
    messagingSenderId: '1041754221282',
    projectId: 'delconnectbase',
    authDomain: 'delconnectbase.firebaseapp.com',
    storageBucket: 'delconnectbase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYSOcuvKQ4-zGAvF9raYiVwIJySqwl34U',
    appId: '1:1041754221282:android:24511d8c65cef0f19e8cbb',
    messagingSenderId: '1041754221282',
    projectId: 'delconnectbase',
    storageBucket: 'delconnectbase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbAWDnbgg95Okm72GkJIRziDjog7WWRe0',
    appId: '1:1041754221282:ios:9713032c1b77352f9e8cbb',
    messagingSenderId: '1041754221282',
    projectId: 'delconnectbase',
    storageBucket: 'delconnectbase.firebasestorage.app',
    iosBundleId: 'com.example.delconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbAWDnbgg95Okm72GkJIRziDjog7WWRe0',
    appId: '1:1041754221282:ios:9713032c1b77352f9e8cbb',
    messagingSenderId: '1041754221282',
    projectId: 'delconnectbase',
    storageBucket: 'delconnectbase.firebasestorage.app',
    iosBundleId: 'com.example.delconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4tKVHikdYaRBEdbT7Rc-GOgAz25Z4qIU',
    appId: '1:1041754221282:web:344f069c62479a5b9e8cbb',
    messagingSenderId: '1041754221282',
    projectId: 'delconnectbase',
    authDomain: 'delconnectbase.firebaseapp.com',
    storageBucket: 'delconnectbase.firebasestorage.app',
  );
}
